pipeline {
  agent {
    kubernetes {
      yamlFile '/kubernetes/KubernetesPod.yaml'
      retries 2
    }
  }
  stages {
    stage('Run maven') {
      steps {
        container('maven') {
          sh 'mvn -version'
        }
        container('busybox') {
          sh '/bin/busybox'
        }
      }
    }
  }
}