pipeline {
  // agent {
  //   kubernetes {
  //     yamlFile 'kubernetes/jenkins-agent.yaml'
  //     retries 2
  //     // name eks-node
  //     // inheritFrom eks-node
  //   }
  agent any
  
  stages {
    stage('Apply Kubernetes files') {
      steps{
        // withKubeConfig([credentialsId: 'user1', serverUrl: 'https://api.k8s.my-company.com']){
        // sh 'kubectl apply -f /kubernetes/deployment.yml'
        // }
        script{
          // kubernetesDeploy(
          //   configs: '/kubernetes/deployment.yml',
          //   kubeconfigId: 'eks-kubeconfig'
          // )
          withKubeConfig([credentialsId: 'eks-kubeconfig']) {
            sh 'kubectl apply -f /kubernetes/deployment.yml'
          }
        }// sh "echo 'hello worl'"
      }
    }
  }
}