pipeline {
  agent {
    kubernetes {
      yamlFile 'kubernetes/jenkins-agent.yaml'
      retries 2
    }
  }
  stages {
    stage('Apply Kubernetes files') {
      steps{
        // withKubeConfig([credentialsId: 'user1', serverUrl: 'https://api.k8s.my-company.com']){
        sh 'kubectl apply -f /kubernetes/deployment.yml'
        // }

        // kubernetesDeploy(
        //   configs: '/kubernetes/deployment.yml'
        // )
        sh "echo 'hello worl'"
      }
    }
  }
}