apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  containers:
  - name: jenkins-agent
    image: jenkins/inbound-agent
    env:
    - name: JENKINS_SECRET
      value: "5fb62e262b341e3b5d49c6bbd3aadef5605f44b3a0340fede8809a72d3b8015d"
    - name: JENKINS_AGENT_NAME
      value: "eks-node"
    - name: JENKINS_AGENT_WORKDIR
      value: "/home/ubuntu/jenkins"
    - name: JENKINS_URL
      value: "http://3.97.12.36:8080"
    command: ["/bin/sh","-c"]
    # ports:
    # - containerPort: 50000
